---
name: Bruce
surname: Bolin
position: "Operations Manager"
address: "Bloomington IN"
profilepic: "./img/2023professionalMe.png"
email: "bruce.bolin@warranttek.com"
phone: 812-430-0184
extrainfo: ENTP
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 4E9AAA
aboutme: "I am a budding leader with a history of managing creative endeavors and delivering superior results. Curiousity, Communication, and Compassion are the skills I leverage most often to navigate the intricacies of  leadership. I love to solve problems and investigate how things are connected. What puzzle do you have for me today?"
header-includes:
  - \hyphenpenalty=10000
  - \exhyphenpenalty=10000
  - \emergencystretch=2em
  - \usepackage{etoolbox}
  - \apptocmd{\endcvitems}{\vspace{3.0mm}}{}{}
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

fmt_when <- function(startMonth, startYear, endMonth, endYear) {
  mapply(function(sm, sy, em, ey) {
    clean <- function(...) {
      x <- unlist(list(...), use.names = FALSE)
      x <- x[!is.na(x)]
      x <- trimws(as.character(x))
      x <- x[nzchar(x)]
      paste(x, collapse = " ")
    }

    paste0(clean(sm, sy), " --> ", clean(em, ey))
  }, startMonth, startYear, endMonth, endYear, USE.NAMES = FALSE)
}

edu_when <- function(startYear, endYear) {
  mapply(function(sy, ey) {
    if (!is.na(sy) && !is.na(ey)) {
      paste0(sy, " --> ", ey)
    } else if (is.na(sy) && !is.na(ey)) {
      paste0("Expected ", ey)
    } else if (!is.na(sy) && is.na(ey)) {
      as.character(sy)
    } else {
      ""
    }
  }, startYear, endYear, USE.NAMES = FALSE)
}

```

# Employment

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = unit, 
    why = detail,
    when = fmt_when(startMonth, startYear, endMonth, endYear),
    where = where
  )

```

# Education

```{r EDUCATION}

edu %>%
  detailed_entries(
    what = focus,
    why = detail,
    when = edu_when(startYear, endYear),
    where = where
  )

```

\pagebreak

# Skills

```{r SKILLS}

skills %>%
  detailed_entries(
    with = area,
    why = detail
  )

```

# Certifications

```{r CERTIFICATIONS}

certifications %>%
  detailed_entries(
    with = area,
    when = year
  )

```

# Hobbies

```{r HOBBIES}
hobbies %>%
  detailed_entries(
    with = passtime,
    when = startYear
  )
```

# Values

```{r VALUES}
values %>%
    detailed_entries(
      with = what
    )
```
